version: "3.8"
services:
  app:
    container_name: backend
    build: ./
    environment:
      PG_HOST: db
      PG_PORT: 5432
    ports:
      - "8088:8080"
    links: 
      - db

  db:
    container_name: db
    image: postgres:14.0
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cs_labworks
    expose: 
      - 5432
    volumes:
      - /home/greatunreal/LABS/Diplom/backend/DB/
    command: bash /home/greatunreal/LABS/Diplom/backend/DB/db_create.sh